<<<<<<< HEAD
<<<<<<< HEAD
=======
version: "3"
>>>>>>> 8364914 (Primeiro commit no branch pr-cicd)
=======
version: "3"
>>>>>>> 83649143cc91188e0f3a7534ff54971c594552c4
services:
  server:
    build: .
    container_name: bia
    ports:
<<<<<<< HEAD
<<<<<<< HEAD
      - 80:8080
=======
=======
>>>>>>> 83649143cc91188e0f3a7534ff54971c594552c4
      - 3001:8080
    links:
      - database
    environment:
      DB_USER: postgres
      DB_PWD: postgres
      DB_HOST: database
      DB_PORT: 5432
  database:
    image: postgres:16.1
    container_name: database
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=bia"
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
<<<<<<< HEAD
>>>>>>> 8364914 (Primeiro commit no branch pr-cicd)
=======
>>>>>>> 83649143cc91188e0f3a7534ff54971c594552c4
